name: Build

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Install Dependencies
                run: |
                    # Install aftman
                    curl -L https://github.com/LPGhatguy/aftman/releases/download/v0.2.7/aftman-0.2.7-linux-x86_64.zip -o aftman.zip
                    unzip aftman.zip
                    chmod +x ./aftman
                    ./aftman self-install
                    source ~/.bashrc
                    yes | aftman install

            -   name: Build
                run: |
                    rojo sourcemap default.project.json --output sourcemap.json
                    wally-package-types --sourcemap sourcemap.json /Packages
                    rojo build --output Matrix.rbxm

            -   name: Upload Artifact(s)
                uses: actions/upload-artifact@v4
                with:
                    name: Matrix
                    path: Matrix.rbxm